spring:
  application:
    name: magdamock-service

magda:
  magdamock:
    magda-mock-test-path: "wiremock"
    soap-test-path:  # directory containing SOAP XML files (absolute path)
    magda-xsd-path: # directory containing SOAP XSD files "src/main/resources/magda.xsd"
    minimum-timeout-millis:
    maximum-timeout-millis:
    enable-timeout: false

management:
  server:
    port: 8081

  endpoint:
    health:
      show-details: always
