spring:
  application:
    name: magdamock-service

magda:
  magdamock:
    magda-mock-test-path: "wiremock"
    soap-test-path:  # directory containing SOAP XML files (absolute path)
    magda-xsd-path: "src/main/resources/magda.xsd"

management:
  server:
    port: 8081

  endpoint:
    health:
      show-details: always
