image:
  name: vlaamseoverheid-magda-docker-public.jfrog.io/magda/magda-base-pipeline:jdk21-latest
  username: $ARTIFACTORY_USER
  password: $ARTIFACTORY_PASSWORD

definitions:
  steps:
    - step: &deploy
        name: Deploy to ...
        deployment: PLACEHOLDER
        caches:
          - maven
        script:
          - export INFRA_REPO='magdamock.service-infra'
          - export IFS=' '
          # Allow overwriting applications in deployments
          - >
            if [[ "$APPS" == "" ]]; then
              export APPS='magdamock-spring'
            fi
          - echo $NAMESPACE > target/namespace  # Necessary for passing namespace to the next steps
          - chmod +x deploy-with-argocd.sh
          - ./deploy-with-argocd.sh
        artifacts:
          - target/namespace
    - step: &release
        name: Release
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - /bin/bash ./release-application.sh
    - step: &dockerRebuildFromTag
        name: Rebuild Docker from tag
        caches:
          - maven
          - docker
        script:
          - export VERSION=$rebuild_git_tag
          # Checkout
          - source "commons.sh"
          - prepare_git
          - git checkout $VERSION
          - mvn -B package io.fabric8:docker-maven-plugin:0.31.0:push -s .m2/settings.xml -Pfat-jar -Pdocker-release
    - step: &sigridPublish
        image: softwareimprovementgroup/sigridci
        name: Publish to Sigrid
        script:
          - git config --global --add safe.directory /opt/atlassian/pipelines/agent/build
          - timeout 10m sigridci.py --customer $SIGRID_CI_ACCOUNT --system $(echo $BITBUCKET_REPO_FULL_NAME | cut -d'/' -f 2 | cut -c 1-45| sed -e "s/\./-/g") --source . --publishonly --include-history
    - step: &sigridCI
        image: softwareimprovementgroup/sigridci
        name: Sigrid CI
        script:
          - git config --global --add safe.directory /opt/atlassian/pipelines/agent/build
          - timeout 10m sigridci.py --customer $SIGRID_CI_ACCOUNT --system $(echo $BITBUCKET_REPO_FULL_NAME | cut -d'/' -f 2 | cut -c 1-45| sed -e "s/\./-/g") --source .
clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: Check
          caches:
            - maven
          script:
            # Only run for released version
            - mvn -B -s .m2/settings.xml org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce -Drules=requireReleaseVersion
            - mkdir -p target
            - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
            - mvn dependency:tree > maven.tree
          artifacts:
            - target/pom_version
            - maven.tree
      - step:
          <<: *sigridPublish
      - step:
          <<: *deploy
          name: Deploy release to TST
          deployment: TST
      - step:
          <<: *deploy
          name: Deploy release to TNI
          deployment: TNI
      - step:
          <<: *deploy
          name: Deploy release to PRD
          trigger: manual
          deployment: PRD
    develop:
      - step:
          name: Maven
          caches:
            - maven
            - docker
          script:
            - export TESTCONTAINERS_RYUK_DISABLED=true
            - export MAVEN_OPTS="-Xmx1024m"
            - mvn -B -U clean deploy sonar:sonar -s .m2/settings.xml -Dbuild=bitbucket -Pfat-jar -Pdocker -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.token=${SONAR_APITOKEN}
            - mkdir -p target
            - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
            - mvn dependency:tree > maven.tree
          artifacts:
            - "**/*.jar"
            - target/pom_version
            - maven.tree
      - step:
          <<: *sigridPublish
      - step:
          <<: *deploy
          name: Deploy to BETA
          deployment: DEV

  pull-requests:
    '**':
      - parallel:
          steps:
            - step:
                name: Maven
                caches:
                  - maven
                script:
                  - export TESTCONTAINERS_RYUK_DISABLED=true
                  - export MAVEN_OPTS="-Xmx1024m"
                  - mvn -B -U clean verify sonar:sonar -s .m2/settings.xml -Dbuild=bitbucket  -Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.token=${SONAR_APITOKEN} -Dsonar.branch.name="$BITBUCKET_BRANCH"
                artifacts:
                  - "**/*.jar"
            - step:
                <<: *sigridCI
  custom:
    maven-release:
      - step: *release
    deploy-released-version:
      - step:
          name: Check
          caches:
            - maven
          script:
            # Only run for released version
            - mvn -B -s .m2/settings.xml org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce -Drules=requireReleaseVersion
            - mkdir -p target
            - mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout > target/pom_version
          artifacts:
            - target/pom_version
      - step:
          <<: *deploy
          name: Deploy release to TST
          deployment: TST
      - step:
          <<: *deploy
          name: Deploy release to TNI
          deployment: TNI
      - step:
          <<: *deploy
          name: Deploy release to PRD
          trigger: manual
          deployment: PRD
    rebuild-docker-from-tag:
      - variables:
          - name: rebuild_git_tag
      - step: *dockerRebuildFromTag
options:
  docker: true
  size: 2x
