services:
  demo:
    image: "vlaamseoverheid-magda-docker-snapshots.jfrog.io/magda/magda.magdamock:latest"
    ports:
      - 8080:8080
    volumes:
     - type: bind
       source: ./application.yml
       target: /application.yml
       read_only: true
     - "./wiremock-data:/data/wiremock"
