FROM eclipse-temurin:25-jre

VOLUME /tmp

COPY target/*.jar /target/

COPY src/main/resources/magda.xsd /data/magda.xsd
COPY src/main/resources/scripts /data/scripts

EXPOSE 8080:8080

RUN apt-get update && apt-get install -y --no-install-recommends git

CMD ["/data/scripts/entrypoint.sh"]
