FROM vlaamseoverheid-magda-docker-public.jfrog.io/magda/vdip-java:${vdip-java.version}

VOLUME /tmp
# The docker image expects this location
COPY target/${project.build.finalName}.jar /opt/app/app.jar
# The helm chart expects this location
COPY target/${project.build.finalName}.jar /target/app.jar

COPY --chown=javauser:javauser src/main/resources/magda.xsd /data/magda.xsd
COPY --chown=javauser:javauser src/main/resources/scripts /data/scripts

EXPOSE 8080:8080

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git
USER javauser

CMD ["/data/scripts/entrypoint.sh"]
