FROM vlaamseoverheid-magda-docker-public.jfrog.io/magda/vdip-java:${vdip-java.version}

VOLUME /tmp

EXPOSE 8080:8080

COPY target/${project.build.finalName}.jar app.jar

CMD ["java", "-jar", "/app.jar"]
